### ISSUE TITLE
Error importing baloo. libpython3.5m.so.1.0: cannot open shared object file

### ISSUE THREAD

**Issue by unbalancedparentheses** [radujica/baloo#25]
Error importing baloo
```unbalanced@hendrix ~> python
Python 3.5.7 (default, Sep 19 2019, 19:54:26)
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import baloo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/__init__.py", line 1, in <module>
    from .core import *
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/core/__init__.py", line 1, in <module>
    from .frame import DataFrame
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/core/frame.py", line 8, in <module>
    from .indexes import Index, MultiIndex
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/core/indexes/__init__.py", line 1, in <module>
    from .base import Index
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/core/indexes/base.py", line 4, in <module>
    from ...core.utils import check_type, infer_dtype, is_scalar, check_weld_bit_array, check_valid_int_slice, \
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/core/utils.py", line 3, in <module>
    from ..weld import WeldObject, weld_count, WeldBit, WeldLong, LazyResult, supported_dtype_chars
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/weld/__init__.py", line 3, in <module>
    from .lazy_result import *
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/weld/lazy_result.py", line 6, in <module>
    from .weld_aggs import weld_aggregate, weld_count
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/weld/weld_aggs.py", line 1, in <module>
    from .weld_utils import create_weld_object, get_weld_obj_id
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/weld/weld_utils.py", line 6, in <module>
    _encoder = NumPyEncoder()
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/site-packages/baloo/weld/convertors/encoders.py", line 138, in __init__
    self.utils = ctypes.PyDLL(ENCODERS_PATH)
  File "/home/unbalanced/.pyenv/versions/3.5.7/lib/python3.5/ctypes/__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
>>>
```

**Comment by radujica** [comment]
I don't see how that could happen. How did you install?

**Comment by unbalancedparentheses** [comment]
```pip install baloo```

We have in linux and os x hosts. Let me know if you need more information or if I could do something else to help.

**Comment by radujica** [comment]
I have retried on the machine Baloo was developed on (a Mint VM) and `pipenv --three install baloo` still works. However, looks like the bug you show does happen when trying `pip3 install baloo` via Ubuntu on my Windows machine.

I can only recommend atm:
- replicating as close as possible my setup, i.e. Python 3.5 and install through pipenv
- or try fixing via ideas [here](https://stackoverflow.com/questions/43333207/python-error-while-loading-shared-libraries-libpython3-4m-so-1-0-cannot-open)
- or using the repo directly

**Comment by unbalancedparentheses** [comment]
Ok will try and I will let you know.
